project_id = "gryxarbwnvmitksyzhvi"

[functions.analyze-sheet]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.extract-table-from-image]
verify_jwt = false

[functions.sellix-chat]
verify_jwt = false
